# NBA Stats Application
# Azure Developer CLI (azd) Configuration

name: nba-stats
metadata:
  template: nba-stats@0.0.1

services:
  api:
    project: services/api
    language: js
    host: containerapp
    docker:
      path: Dockerfile
      context: .
    
  frontend:
    project: frontend
    language: js
    host: containerapp
    docker:
      path: Dockerfile
      context: .

infra:
  provider: bicep
  path: ./infra
  module: main
  parameters:
    dev: ./infra/parameters/dev.bicepparam
    test: ./infra/parameters/test.bicepparam
    prod: ./infra/parameters/prod.bicepparam

pipeline:
  provider: azdo

hooks:
  postprovision:
    posix:
      shell: sh
      run: |
        echo "Post-provision hook: Seeding Key Vault secrets"
        
        # Get Key Vault name from azd environment
        KEY_VAULT_NAME=$(azd env get-values | grep KEY_VAULT_NAME | cut -d'=' -f2 | tr -d '"')
        
        if [ ! -z "$KEY_VAULT_NAME" ]; then
          echo "Seeding secrets to Key Vault: $KEY_VAULT_NAME"
          bash ./infra/scripts/seed-secrets.sh --key-vault "$KEY_VAULT_NAME" --api-key "$NBA_API_KEY"
        else
          echo "Warning: KEY_VAULT_NAME not found in environment"
        fi
        
        echo "Initializing database schema"
        POSTGRES_FQDN=$(azd env get-values | grep POSTGRES_SERVER_FQDN | cut -d'=' -f2 | tr -d '"')
        
        if [ ! -z "$POSTGRES_FQDN" ]; then
          bash ./infra/scripts/init-database.sh \
            --server "$POSTGRES_FQDN" \
            --database "nba_stats" \
            --username "nbastatsadmin" \
            --password "$POSTGRES_ADMIN_PASSWORD"
        fi
        
        echo "Post-provision complete"

