# NBA Stats Infrastructure Deployment Pipeline
# Deploys Azure infrastructure using Bicep IaC
# Implements what-if analysis, approval gates, and phased deployment

name: 'Infra-Deploy-$(Date:yyyyMMdd)-$(Rev:r)'

trigger:
  branches:
    include:
      - main
  paths:
    include:
      - infra/**
      - pipelines/infra-deploy.yml

pr:
  branches:
    include:
      - main
  paths:
    include:
      - infra/**
      - pipelines/infra-deploy.yml

variables:
  - name: azureSubscription
    value: 'azure-nba-stats-connection'
  - name: location
    value: 'swedencentral'
  - name: vmImage
    value: 'ubuntu-latest'

stages:
  # ==============================================================================
  # STAGE 1: Deploy to Dev Environment
  # ==============================================================================
  - stage: Deploy_Dev
    displayName: 'Deploy: Dev'
    dependsOn: []
    condition: and(succeeded(), ne(variables['Build.Reason'], 'PullRequest'))
    jobs:
      - deployment: DeployDev
        displayName: 'Deploy Infrastructure (Dev)'
        pool:
          vmImage: $(vmImage)
        environment: 'nba-stats-dev'
        strategy:
          runOnce:
            deploy:
              steps:
                - checkout: self

                - task: AzureCLI@2
                  displayName: 'Deploy Bicep Template (Dev)'
                  inputs:
                    azureSubscription: $(azureSubscription)
                    scriptType: 'bash'
                    scriptLocation: 'inlineScript'
                    inlineScript: |
                      set -e  # Exit on error
                      
                      echo "Deploying to dev environment..."
                      
                      # Run deployment and capture outputs
                      DEPLOYMENT_OUTPUT=$(az deployment sub create \
                        --name "deploy-dev-$(Build.BuildNumber)" \
                        --location "$(location)" \
                        --template-file "$(Build.SourcesDirectory)/infra/main.bicep" \
                        --parameters "$(Build.SourcesDirectory)/infra/parameters/dev.bicepparam" \
                        --parameters location='$(location)' \
                        --parameters postgresAdminPassword='$(POSTGRES_ADMIN_PASSWORD)' \
                        --parameters nbaApiKey='$(NBA_API_KEY)' \
                        --query '{postgresServerFqdn:properties.outputs.postgresServerFqdn.value,resourceGroupName:properties.outputs.resourceGroupName.value,containerRegistryName:properties.outputs.containerRegistryName.value,containerRegistryLoginServer:properties.outputs.containerRegistryLoginServer.value,apiUrl:properties.outputs.apiUrl.value}' \
                        --output json)
                      
                      # Save outputs to file
                      echo "$DEPLOYMENT_OUTPUT" > "$(Build.ArtifactStagingDirectory)/deployment-dev.json"
                      
                      echo "Deployment complete. Outputs:"
                      cat "$(Build.ArtifactStagingDirectory)/deployment-dev.json"

                - task: PublishPipelineArtifact@1
                  displayName: 'Publish Deployment Outputs (Dev)'
                  inputs:
                    targetPath: '$(Build.ArtifactStagingDirectory)/deployment-dev.json'
                    artifact: 'deployment-dev'
                    publishLocation: 'pipeline'

                - task: AzureCLI@2
                  displayName: 'Initialize Database Schema (Dev)'
                  inputs:
                    azureSubscription: $(azureSubscription)
                    scriptType: 'bash'
                    scriptLocation: 'inlineScript'
                    inlineScript: |
                      # Extract PostgreSQL server FQDN from deployment outputs
                      POSTGRES_FQDN=$(cat "$(Build.ArtifactStagingDirectory)/deployment-dev.json" | jq -r '.postgresServerFqdn')
                      
                      echo "Initializing database schema..."
                      echo "PostgreSQL Server: $POSTGRES_FQDN"
                      
                      # Run database initialization script
                      bash "$(Build.SourcesDirectory)/infra/scripts/init-database.sh" \
                        --server "$POSTGRES_FQDN" \
                        --database "nba_stats" \
                        --username "nbastatsadmin" \
                        --password "$(POSTGRES_ADMIN_PASSWORD)" \
                        --force

                - task: Bash@3
                  displayName: 'Tag Deployment'
                  inputs:
                    targetType: 'inline'
                    script: |
                      # Configure git identity using the commit author or person who triggered the build
                      # This provides proper audit trail and accountability
                      COMMIT_EMAIL=$(git log -1 --pretty=format:'%ae')
                      COMMIT_NAME=$(git log -1 --pretty=format:'%an')
                      
                      git config user.email "${COMMIT_EMAIL}"
                      git config user.name "${COMMIT_NAME}"
                      
                      echo "Tagging deployment as: ${COMMIT_NAME} <${COMMIT_EMAIL}>"
                      
                      # Create and push tag
                      git tag -a "infra-dev-$(Build.BuildNumber)" -m "Infrastructure deployment to dev - $(Build.BuildNumber)"
                      git push origin "infra-dev-$(Build.BuildNumber)"
                      echo "Tagged deployment: infra-dev-$(Build.BuildNumber)"

  # ==============================================================================
  # STAGE 2: Deploy to Test Environment (Manual Approval Required)
  # ==============================================================================
  - stage: Deploy_Test
    displayName: 'Deploy: Test'
    dependsOn: Deploy_Dev
    condition: and(succeeded(), ne(variables['Build.Reason'], 'PullRequest'))
    jobs:
      - deployment: DeployTest
        displayName: 'Deploy Infrastructure (Test)'
        pool:
          vmImage: $(vmImage)
        environment: 'nba-stats-test' # Requires manual approval in Azure DevOps
        strategy:
          runOnce:
            deploy:
              steps:
                - checkout: self

                - task: AzureCLI@2
                  displayName: 'Deploy Bicep Template (Test)'
                  inputs:
                    azureSubscription: $(azureSubscription)
                    scriptType: 'bash'
                    scriptLocation: 'inlineScript'
                    inlineScript: |
                      set -e  # Exit on error
                      
                      echo "Deploying to test environment..."
                      
                      # Run deployment and capture outputs
                      DEPLOYMENT_OUTPUT=$(az deployment sub create \
                        --name "deploy-test-$(Build.BuildNumber)" \
                        --location "$(location)" \
                        --template-file "$(Build.SourcesDirectory)/infra/main.bicep" \
                        --parameters "$(Build.SourcesDirectory)/infra/parameters/test.bicepparam" \
                        --parameters location='$(location)' \
                        --parameters postgresAdminPassword='$(POSTGRES_ADMIN_PASSWORD)' \
                        --parameters nbaApiKey='$(NBA_API_KEY)' \
                        --query '{postgresServerFqdn:properties.outputs.postgresServerFqdn.value,resourceGroupName:properties.outputs.resourceGroupName.value,containerRegistryName:properties.outputs.containerRegistryName.value,containerRegistryLoginServer:properties.outputs.containerRegistryLoginServer.value,apiUrl:properties.outputs.apiUrl.value}' \
                        --output json)
                      
                      # Save outputs to file
                      echo "$DEPLOYMENT_OUTPUT" > "$(Build.ArtifactStagingDirectory)/deployment-test.json"
                      
                      echo "Deployment complete. Outputs:"
                      cat "$(Build.ArtifactStagingDirectory)/deployment-test.json"

                - task: PublishPipelineArtifact@1
                  displayName: 'Publish Deployment Outputs (Test)'
                  inputs:
                    targetPath: '$(Build.ArtifactStagingDirectory)/deployment-test.json'
                    artifact: 'deployment-test'
                    publishLocation: 'pipeline'

                - task: AzureCLI@2
                  displayName: 'Initialize Database Schema (Test)'
                  inputs:
                    azureSubscription: $(azureSubscription)
                    scriptType: 'bash'
                    scriptLocation: 'inlineScript'
                    inlineScript: |
                      POSTGRES_FQDN=$(cat "$(Build.ArtifactStagingDirectory)/deployment-test.json" | jq -r '.postgresServerFqdn')
                      
                      echo "Initializing database schema..."
                      echo "PostgreSQL Server: $POSTGRES_FQDN"
                      
                      bash "$(Build.SourcesDirectory)/infra/scripts/init-database.sh" \
                        --server "$POSTGRES_FQDN" \
                        --database "nba_stats" \
                        --username "nbastatsadmin" \
                        --password "$(POSTGRES_ADMIN_PASSWORD)" \
                        --force

                - task: Bash@3
                  displayName: 'Tag Deployment'
                  inputs:
                    targetType: 'inline'
                    script: |
                      # Configure git identity using the commit author or person who triggered the build
                      # This provides proper audit trail and accountability
                      COMMIT_EMAIL=$(git log -1 --pretty=format:'%ae')
                      COMMIT_NAME=$(git log -1 --pretty=format:'%an')
                      
                      git config user.email "${COMMIT_EMAIL}"
                      git config user.name "${COMMIT_NAME}"
                      
                      echo "Tagging deployment as: ${COMMIT_NAME} <${COMMIT_EMAIL}>"
                      
                      # Create and push tag
                      git tag -a "infra-test-$(Build.BuildNumber)" -m "Infrastructure deployment to test - $(Build.BuildNumber)"
                      git push origin "infra-test-$(Build.BuildNumber)"
                      echo "Tagged deployment: infra-test-$(Build.BuildNumber)"

  # ==============================================================================
  # STAGE 3: Deploy to Production Environment (Manual Approval Required)
  # ==============================================================================
  - stage: Deploy_Prod
    displayName: 'Deploy: Prod'
    dependsOn: Deploy_Test
    condition: and(succeeded(), ne(variables['Build.Reason'], 'PullRequest'))
    jobs:
      - deployment: DeployProd
        displayName: 'Deploy Infrastructure (Prod)'
        pool:
          vmImage: $(vmImage)
        environment: 'nba-stats-prod' # Requires manual approval
        strategy:
          runOnce:
            deploy:
              steps:
                - checkout: self

                - task: AzureCLI@2
                  displayName: 'Deploy Bicep Template (Prod)'
                  inputs:
                    azureSubscription: $(azureSubscription)
                    scriptType: 'bash'
                    scriptLocation: 'inlineScript'
                    inlineScript: |
                      set -e  # Exit on error
                      
                      echo "Deploying to production environment..."
                      
                      # Run deployment and capture outputs
                      DEPLOYMENT_OUTPUT=$(az deployment sub create \
                        --name "deploy-prod-$(Build.BuildNumber)" \
                        --location "$(location)" \
                        --template-file "$(Build.SourcesDirectory)/infra/main.bicep" \
                        --parameters "$(Build.SourcesDirectory)/infra/parameters/prod.bicepparam" \
                        --parameters location='$(location)' \
                        --parameters postgresAdminPassword='$(POSTGRES_ADMIN_PASSWORD)' \
                        --parameters nbaApiKey='$(NBA_API_KEY)' \
                        --query '{postgresServerFqdn:properties.outputs.postgresServerFqdn.value,resourceGroupName:properties.outputs.resourceGroupName.value,containerRegistryName:properties.outputs.containerRegistryName.value,containerRegistryLoginServer:properties.outputs.containerRegistryLoginServer.value,apiUrl:properties.outputs.apiUrl.value}' \
                        --output json)
                      
                      # Save outputs to file
                      echo "$DEPLOYMENT_OUTPUT" > "$(Build.ArtifactStagingDirectory)/deployment-prod.json"
                      
                      echo "Deployment complete. Outputs:"
                      cat "$(Build.ArtifactStagingDirectory)/deployment-prod.json"

                - task: PublishPipelineArtifact@1
                  displayName: 'Publish Deployment Outputs (Prod)'
                  inputs:
                    targetPath: '$(Build.ArtifactStagingDirectory)/deployment-prod.json'
                    artifact: 'deployment-prod'
                    publishLocation: 'pipeline'

                - task: AzureCLI@2
                  displayName: 'Initialize Database Schema (Prod)'
                  inputs:
                    azureSubscription: $(azureSubscription)
                    scriptType: 'bash'
                    scriptLocation: 'inlineScript'
                    inlineScript: |
                      POSTGRES_FQDN=$(cat "$(Build.ArtifactStagingDirectory)/deployment-prod.json" | jq -r '.postgresServerFqdn')
                      
                      echo "Initializing database schema..."
                      echo "PostgreSQL Server: $POSTGRES_FQDN"
                      
                      bash "$(Build.SourcesDirectory)/infra/scripts/init-database.sh" \
                        --server "$POSTGRES_FQDN" \
                        --database "nba_stats" \
                        --username "nbastatsadmin" \
                        --password "$(POSTGRES_ADMIN_PASSWORD)" \
                        --force

                - task: Bash@3
                  displayName: 'Tag Deployment'
                  inputs:
                    targetType: 'inline'
                    script: |
                      # Configure git identity using the commit author or person who triggered the build
                      # This provides proper audit trail and accountability
                      COMMIT_EMAIL=$(git log -1 --pretty=format:'%ae')
                      COMMIT_NAME=$(git log -1 --pretty=format:'%an')
                      
                      git config user.email "${COMMIT_EMAIL}"
                      git config user.name "${COMMIT_NAME}"
                      
                      echo "Tagging deployment as: ${COMMIT_NAME} <${COMMIT_EMAIL}>"
                      
                      # Create and push tag
                      git tag -a "infra-prod-$(Build.BuildNumber)" -m "Infrastructure deployment to prod - $(Build.BuildNumber)"
                      git push origin "infra-prod-$(Build.BuildNumber)"
                      echo "##vso[task.setvariable variable=DEPLOYMENT_TAG]infra-prod-$(Build.BuildNumber)"

                - task: Bash@3
                  displayName: 'Deployment Summary'
                  inputs:
                    targetType: 'inline'
                    script: |
                      echo "=========================================="
                      echo "  NBA Stats Infrastructure Deployment"
                      echo "=========================================="
                      echo "Environment: Production"
                      echo "Build Number: $(Build.BuildNumber)"
                      echo "Deployment Tag: $(DEPLOYMENT_TAG)"
                      echo ""
                      echo "Deployment outputs saved to pipeline artifacts"
                      echo "=========================================="
